### ISSUE TITLE
prompt token count exceeds the limit of 64000

### ISSUE THREAD

**Issue by DimashOne** [microsoft/GitHub-Copilot-for-Azure#23]
An error occurred on the server while streaming results.

`2024-11-16 00:44:25.918 [error] [Microsoft.Azure.CopilotForAzure.AIService.Orchestration.OrchestratorBase] Error while processing request.
System.ClientModel.ClientResultException: HTTP 400 (: )

prompt token count of 65204 exceeds the limit of 64000
   at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.<>c__DisplayClass12_0.<<CompleteChatStreamingAsync>g__sendRequestAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenAI.Chat.InternalAsyncStreamingChatCompletionUpdateCollection.GetRawPagesAsync()+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.Azure.CopilotForAzure.AIService.Orchestration.OrchestratorBase.ChatAsync(ChatHistory history, ChannelWriter`1 responseChannelWriter, KernelParameters kernelParameters, CancellationToken cancellationToken)
   at Microsoft.Azure.CopilotForAzure.AIService.Orchestration.OrchestratorBase.ChatAsync(ChatHistory history, ChannelWriter`1 responseChannelWriter, KernelParameters kernelParameters, CancellationToken cancellationToken)
`

**Comment by bwateratmsft** [comment]
@DimashOne can you share what query you used that hit this issue? It would help us to know what plugin(s) got invoked that overloaded the context window.

**Comment by DimashOne** [comment]
@bwateratmsft 
`@azure test`

**Comment by DimashOne** [comment]
@bwateratmsft 
next query `@azure test` failed with increased token count: 

`prompt token count of 65209 exceeds the limit of 64000`

**Comment by bwateratmsft** [comment]
Is there a very long conversation history leading up to this entry, or is there a large file getting attached?
![Image](https://github.com/user-attachments/assets/30664bb0-4e46-4a04-94b3-d93df02dece6)

**Comment by DimashOne** [comment]
@bwateratmsft  no, only text chat query without files

2024-11-16 08:21:05.167 [info] Received chat: test2
2024-11-16 08:21:07.819 [error] [Microsoft.Azure.CopilotForAzure.AIService.Orchestration.OrchestratorBase] Error while processing request.
System.ClientModel.ClientResultException: HTTP 400 (: )

prompt token count of 65221 exceeds the limit of 64000
   at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.<>c__DisplayClass12_0.<<CompleteChatStreamingAsync>g__sendRequestAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenAI.Chat.InternalAsyncStreamingChatCompletionUpdateCollection.GetRawPagesAsync()+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.Azure.CopilotForAzure.AIService.Orchestration.OrchestratorBase.ChatAsync(ChatHistory history, ChannelWriter`1 responseChannelWriter, KernelParameters kernelParameters, CancellationToken cancellationToken)
   at Microsoft.Azure.CopilotForAzure.AIService.Orchestration.OrchestratorBase.ChatAsync(ChatHistory history, ChannelWriter`1 responseChannelWriter, KernelParameters kernelParameters, CancellationToken cancellationToken)

GitHub Copilot chat without `@azure` works well

**Comment by charris-msft** [comment]
@DimashOne - would you mind starting a new chat (ctrl+L or cmd+L) and sending us a screenshot or screen recording so we can see what you're seeing?

**Comment by DimashOne** [comment]
@charris-msft there is no error, when I start a new chat. It looks like the issue appears with long-live chats.

**Comment by charris-msft** [comment]
@DimashOne - That's what we suspected, but thank you for confirming.

It looks like we need to provide a clear error message when the chat history exceeds the allowed limit.

Thank you for your help!

**Comment by kvenkatrajan** [comment]
* lower to 60K
* provide a clear error message when the chat history exceeds the allowed limit, informing people to start a new chat.

**Comment by bwateratmsft** [comment]
We already do the second:

![Image](https://github.com/user-attachments/assets/b6339c3a-79cc-45f7-bd86-ae6f44e1bb99)

**Comment by bwateratmsft** [comment]
Closing this, we added some buffer space.
